"""LangGraph ReAct agent builder.

Constructs a compiled StateGraph with two nodes:

    START → agent (LLM) ─── has tool_calls? ──→ tools (execute) → agent
                         └── no tool_calls  ──→ END

This is the standard LangGraph ReAct pattern.  The agent node calls the
LLM with tools bound, and the conditional edge routes back to tools or
terminates when the LLM returns a final answer.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from langchain_openai import ChatOpenAI
from langgraph.graph import END, StateGraph
from langgraph.prebuilt import ToolNode

from app.config import settings
from app.engine.state import AgentState

if TYPE_CHECKING:
    from langchain_core.tools import BaseTool
    from langgraph.graph.state import CompiledStateGraph


def _should_continue(state: AgentState) -> str:
    """Route after the agent node: continue to tools or finish."""
    last_message = state["messages"][-1]
    if hasattr(last_message, "tool_calls") and last_message.tool_calls:
        return "tools"
    return END


def build_agent(
    tools: list[BaseTool],
    system_prompt: str,
    model: str = "gpt-4o",
) -> CompiledStateGraph:
    """Build and compile a LangGraph ReAct agent.

    Parameters
    ----------
    tools : list[BaseTool]
        LangChain tools the agent can invoke (generated by tool_generator).
    system_prompt : str
        System prompt describing the agent's goal and available platforms.
    model : str
        OpenAI model name (default: gpt-4o).

    Returns
    -------
    CompiledStateGraph
        A compiled LangGraph that can be invoked or streamed.
    """
    llm = ChatOpenAI(
        model=model,
        api_key=settings.OPENAI_API_KEY,
        temperature=0,
    ).bind_tools(tools)

    async def agent_node(state: AgentState) -> dict:
        """Call the LLM with the current message history."""
        messages = state["messages"]
        # Prepend system prompt if not already present
        from langchain_core.messages import SystemMessage

        if not messages or not isinstance(messages[0], SystemMessage):
            messages = [SystemMessage(content=system_prompt)] + list(messages)

        response = await llm.ainvoke(messages)
        return {"messages": [response]}

    graph = StateGraph(AgentState)

    # Add nodes
    graph.add_node("agent", agent_node)
    graph.add_node("tools", ToolNode(tools))

    # Set entry point
    graph.set_entry_point("agent")

    # Conditional edge: agent → tools or END
    graph.add_conditional_edges("agent", _should_continue, {"tools": "tools", END: END})

    # Tools always route back to agent
    graph.add_edge("tools", "agent")

    return graph.compile()
